export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const GET_PRODUCT_QUANTITY = "GET_PRODUCT_QUANTITY";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
